const { appendFile } = require('node:fs').promises

const gameTitles = [
  'The Oregon Trail',
  'Pong',
  'Zork',
  'Space Invaders',
  "Shoot 'em up",
  'Asteroids',
  "Shoot 'em up",
  'Adventure',
  'Missile Command',
  "Shoot 'em up",
  'Pac-Man',
  'Centipede',
  "Shoot 'em up",
  'Defender',
  "Shoot 'em up",
  'Donkey Kong',
  'Frogger',
  'Galaga',
  "Shoot 'em up",
  "Shoot 'em up",
  'Joust',
  'Ms. Pac-Man',
  'Pitfall!',
  'Robotron: 2084',
  "Shoot 'em up",
  'Lode Runner',
  "Shoot 'em up",
  'Tetris',
  'Gauntlet',
  "Ghosts'n Goblins",
  'Super Mario Bros.',
  'Bubble Bobble',
  'The Legend of Zelda',
  'Out Run',
  'Contra',
  'Run and gun',
  'Double Dragon',
  "Beat 'em up",
  "Mike Tyson's Punch-Out!!",
  'R-Type',
  "Shoot 'em up",
  "Sid Meier's Pirates!",
  'Mega Man 2',
  'Ninja Gaiden',
  'Super Mario Bros. 3',
  'Final Fight',
  "Beat 'em up",
  'Populous',
  'Prince of Persia',
  'SimCity',
  'The Secret of Monkey Island',
  'Super Mario World',
  'Another World',
  'Civilization',
  'The Legend of Zelda: A Link to the Past',
  'Lemmings',
  "Monkey Island 2: LeChuck's Revenge",
  'Sonic the Hedgehog',
  'Street Fighter II',
  'Super Castlevania IV',
  'Alone in the Dark',
  'Survival horror',
  'Contra III: The Alien Wars',
  'Run and gun',
  'Dune II',
  'Flashback',
  'Indiana Jones and the Fate of Atlantis',
  'Mortal Kombat',
  'Sensible Soccer',
  'Sonic the Hedgehog 2',
  'Star Control II',
  'Streets of Rage 2',
  "Beat 'em up",
  'Super Mario Kart',
  'Virtua Racing',
  'Wolfenstein 3D',
  'Day of the Tentacle',
  'Daytona USA',
  'Doom',
  'Gunstar Heroes',
  'Run and gun',
  "The Legend of Zelda: Link's Awakening",
  'Mega Man X',
  'Mortal Kombat II',
  'Myst',
  'NBA Jam',
  'Phantasy Star IV',
  'Secret of Mana',
  'SimCity 2000',
  'Star Fox',
  "Shoot 'em up",
  'Donkey Kong Country',
  'Doom II',
  'EarthBound',
  'Final Fantasy VI',
  'Sega Rally Championship',
  'Sensible World of Soccer',
  'Super Metroid',
  'X-COM: UFO Defense',
  'Chrono Trigger',
  'Command &amp; Conquer',
  'MechWarrior 2: 31st Century Combat',
  'Warcraft II: Tides of Darkness',
  "Yoshi's Island",
  'Civilization II',
  'Command &amp; Conquer: Red Alert',
  'Duke Nukem 3D',
  'Mario Kart 64',
  'Nights into Dreams...',
  'PaRappa the Rapper',
  'Quake',
  'Resident Evil',
  'Survival horror',
  'Super Mario 64',
  'Tekken 3',
  'Tomb Raider',
  'Wave Race 64',
  'Age of Empires',
  'Castlevania: Symphony of the Night',
  'Diablo',
  'Fallout',
  'Final Fantasy Tactics',
  'Final Fantasy VII',
  'GoldenEye 007',
  'Gran Turismo',
  'Quake II',
  'Star Fox 64',
  "Shoot 'em up",
  'Star Wars Jedi Knight: Dark Forces II',
  'Total Annihilation',
  'Ultima Online',
  "Baldur's Gate",
  'Crash Bandicoot: Warped',
  'Fallout 2',
  'Grim Fandango',
  'Half-Life',
  'The Legend of Zelda: Ocarina of Time',
  'Metal Gear Solid',
  'Resident Evil 2',
  'Survival horror',
  'SoulCalibur',
  'StarCraft',
  'Suikoden II',
  'Thief: The Dark Project',
  'Age of Empires II',
  'EverQuest',
  'Planescape: Torment',
  'Quake III Arena',
  'Shenmue',
  'Silent Hill',
  'Survival horror',
  'Unreal Tournament',
  "Baldur's Gate II: Shadows of Amn",
  'Counter-Strike',
  'Deus Ex',
  'Diablo II',
  'Jet Set Radio',
  "The Legend of Zelda: Majora's Mask",
  'The Sims',
  'Thief II: The Metal Age',
  "Tony Hawk's Pro Skater 2",
  'Advance Wars',
  'Animal Crossing',
  'Devil May Cry',
  'Final Fantasy X',
  'Gran Turismo 3: A-Spec',
  'Grand Theft Auto III',
  'Halo: Combat Evolved',
  'Ico',
  'Ikaruga',
  "Shoot 'em up",
  'Max Payne',
  'Metal Gear Solid 2: Sons of Liberty',
  'Phoenix Wright: Ace Attorney',
  "Shoot 'em up",
  'Silent Hill 2',
  'Survival horror',
  'Super Smash Bros. Melee',
  "Tony Hawk's Pro Skater 3",
  'Battlefield 1942',
  'The Elder Scrolls III: Morrowind',
  "Eternal Darkness: Sanity's Requiem",
  'Survival horror',
  'Grand Theft Auto: Vice City',
  'Kingdom Hearts',
  'The Legend of Zelda: The Wind Waker',
  'Metroid Prime',
  'Soulcalibur II',
  "Tom Clancy's Splinter Cell",
  'Warcraft III: Reign of Chaos',
  'Beyond Good &amp; Evil',
  'F-Zero GX',
  'Max Payne 2: The Fall of Max Payne',
  'Prince of Persia: The Sands of Time',
  'Star Wars: Knights of the Old Republic',
  'WarioWare, Inc.: Mega Microgames!',
  'Burnout 3: Takedown',
  'The Chronicles of Riddick: Escape from Butcher Bay',
  'Dragon Quest VIII',
  'Gran Turismo 4',
  'Grand Theft Auto: San Andreas',
  'Half-Life 2',
  'Halo 2',
  'Katamari Damacy',
  'Metal Gear Solid 3: Snake Eater',
  'Rome: Total War',
  'The Sims 2',
  'World of Warcraft',
  'Call of Duty 2',
  'Civilization IV',
  "Devil May Cry 3: Dante's Awakening",
  'God of War',
  'Guitar Hero',
  'Psychonauts',
  'Resident Evil 4',
  'Survival horror',
  'Shadow of the Colossus',
  "Tom Clancy's Splinter Cell: Chaos Theory",
  'Company of Heroes',
  'The Elder Scrolls IV: Oblivion',
  'Gears of War',
  'Hitman: Blood Money',
  'The Legend of Zelda: Twilight Princess',
  'Ōkami',
  'Wii Sports',
  'BioShock',
  'Call of Duty 4: Modern Warfare',
  'God of War II',
  'Halo 3',
  'Mass Effect',
  'Portal',
  'Rock Band',
  'Super Mario Galaxy',
  'Team Fortress 2',
  'The World Ends with You',
  'Braid',
  'Burnout Paradise',
  'Dead Space',
  'Survival horror',
  'Fallout 3',
  'Gears of War 2',
  'Grand Theft Auto IV',
  'Left 4 Dead',
  'LittleBigPlanet',
  'Persona 4',
  'Rock Band 2',
  'Spelunky',
  'Street Fighter IV',
  'Valkyria Chronicles',
  'Angry Birds',
  "Assassin's Creed II",
  'Batman: Arkham Asylum',
  'Bayonetta',
  'Borderlands',
  "Demon's Souls",
  'Dragon Age: Origins',
  'League of Legends',
  'Left 4 Dead 2',
  'Plants vs. Zombies',
  'Tower defense',
  'Uncharted 2: Among Thieves',
  'God of War III',
  'Heavy Rain',
  'Limbo',
  'Mass Effect 2',
  'Red Dead Redemption',
  'Rock Band 3',
  'StarCraft II: Wings of Liberty',
  'Super Mario Galaxy 2',
  'Super Meat Boy',
  'Xenoblade Chronicles',
  'Batman: Arkham City',
  'Dark Souls',
  'The Elder Scrolls V: Skyrim',
  'Minecraft',
  'Sandbox',
  'Portal 2',
  'Dishonored',
  'Far Cry 3',
  'Journey',
  'Hotline Miami',
  'The Walking Dead',
  'XCOM: Enemy Unknown',
  'BioShock Infinite',
  'Dota 2',
  'Grand Theft Auto V',
  'The Last of Us',
  'Destiny',
  'Shovel Knight',
  'Bloodborne',
  'Undertale',
  'The Witcher III: Wild Hunt',
  'Inside',
  'Overwatch',
  'Stardew Valley',
  "Uncharted 4: A Thief's End",
  'The Legend of Zelda: Breath of the Wild',
  'Super Mario Odyssey',
  'God of War',
  'Red Dead Redemption 2'
]

function randomDate(date1, date2) {
  function randomValueBetween(min, max) {
    return Math.random() * (max - min) + min
  }
  var date1 = date1 || '01-01-1970'
  var date2 = date2 || new Date().toLocaleDateString()
  date1 = new Date(date1).getTime()
  date2 = new Date(date2).getTime()
  if (date1 > date2) {
    return new Date(randomValueBetween(date2, date1)).toLocaleDateString()
  } else {
    return new Date(randomValueBetween(date1, date2)).toLocaleDateString()
  }
}

const mediaTypes = ['Digital', 'Physical']

const parsedList = gameTitles.map((title, index) => {
  return {
    id: index + 1,
    name: title,
    purchase_date: new Date(randomDate('01/01/2010', '12/31/2023')).toISOString(),
    media_type: mediaTypes[Math.round(Math.random())],
    store: Math.floor(Math.random() * 4) + 1,
    value: Number((Math.random() * 300 + 10).toFixed(2))
  }
})

const gen = async () => {
  await appendFile('./db.json', JSON.stringify(parsedList, null, 2), { encoding: 'utf8' })
}

gen()
